### ISSUE TITLE
support hvsock

### ISSUE THREAD

**Issue by CzBiX** [Apache553/ssh-agent-bridge#1]
可以添加支持 hvsock，这样在 WSL2 下安装 socat 就可以用了，免去了自行编译的步骤。
参考 https://github.com/buptczq/WinCryptSSHAgent/blob/master/app/vsock.go

**Comment by Apache553** [comment]
原来 socat 能够支持 AF_HYPERV 的啊！没有怎么看 socat 的文档，就自己造了一套轮子。如果可以使用 Linux 原生的工具那当然是极好的。相关的支持应该会在未来加入。谢谢您的提议！😊

**Comment by Apache553** [comment]
已经添加了对 hvsock 的支持。

**Comment by CzBiX** [comment]
感觉有了 0614ac3f18700c8db0207aab064064b72e263b9f 才算完美的解决啦。
