### ISSUE TITLE
wsl2 helper fails to bind to socket if listen path has symbolic link

### ISSUE THREAD

**Issue by KireinaHoro** [Apache553/ssh-agent-bridge#2]
The helper fails to start if the local listen path (`-l`) contains a parent directory that's a symlink.  For example, if `~/.ssh` is a symbolic link:

```
bind(3, {sa_family=AF_UNIX, sun_path="~/.ssh/agent.socket"}, 110) = -1 ENOENT (No such file or directory)
```

**Comment by KireinaHoro** [comment]
I got it.  The problem is not the symlink but the `~`: this was not expanded in my zshrc.  Please consider using `$HOME` in README instead of `~` as the example.

**Comment by Apache553** [comment]
I have used bash only so I don't know the difference how they handle `~`. The readme has been updated. Thanks for your help!
